### ISSUE TITLE
star 先 作者有没有计划加这些功能？

### ISSUE THREAD

**Issue by jamninetyfive** [Lizhooh/react-native-ivideo#1]
全屏模式/嵌入模式/浮动模式随意切换(支持根据设备自动旋转)
全屏模式支持横屏全屏和竖屏全屏
定制手势：播放/暂停(全屏/嵌入模式双击，浮动模式单击)，浮动和全屏切换（双击），音量/亮度调节（上下滑动），进度调节（左右滑动）
播放器控件皮肤自定义（自带一套浮动皮肤，嵌入和全屏用的一套皮肤）
支持广告功能
支持自定义控制按钮？比如选集，比如播放倍速等等。

一直在rn版本找不到这样的一个播放器。。。

**Comment by Lizhooh** [comment]
@jamninetyfive 
这些功能都可以利用 **动画** 和 **手势** API 实现，有些可能需要编写 `Java` 层的代码。
我目前没有这方面的刚需，因此，暂时就不考虑这方面的计划了 ~~~。

像这种功能，基于 React Native 实现的，应该有团队做了，可能是没开源出来。QaQ

**Comment by jamninetyfive** [comment]
好的 谢谢你了 我们已经解决了 @Lizhooh
